# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    strategy:
      matrix:
          os: [windows-latest]
          python-version: ['3.7.7']
    runs-on: windows-latest
  
    steps:
      - name: Set current date as env variable
        run: |
          echo "current_date=(Get-Date).ToString("yyyy-MM-dd")" >> $GITHUB_ENV
          
      - name: Echo current date
        run: |
          echo "${{ env.current_date }}"
